site_name: NeuralNetsLite.jl

site_description: Simple Neural Networks library written in Julia

repo_url: https://github.com/prcastro/NeuralNetsLite.jl

pages:
- 'Introduction': 'index.md'
- Usage:
    - 'Preparing the dataset': 'usage/data.md'
    - 'Creating the network': 'usage/network.md'
    - 'Predicting and training': 'usage/training.md'
    - 'Measuring performance': 'usage/performance.md'
- Reference:
    - 'API Reference': 'reference/api.md'
- Developing:
    - 'Extending the library': 'developing/extending.md'

extra_javascript:
    - http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
    - mdx_math
